### ISSUE TITLE
Create unit test to package Mapping

### ISSUE THREAD

**Issue by OlhenShu** [OlhenShu/ProjectStage_Team2_May#300]
Create unit test to GreenCityMVP service/src/main/java/greencity/mapping

1. - [x] CategoryDtoMapper
2.  - [x] CategoryDtoResponseMapper
3. - [x] CustomHabitMapper
4. - [x] CustomShoppingListMapper
5. - [x] CustomShoppingListResponseDtoMapper
6. - [x] EcoNewsAuthorDtoMapper
7. - [x] EcoNewsCommentDtoMapper
8. - [x] EcoNewsCommentVOMapper
9. - [x] EcoNewsDtoMapper
10. - [x] EcoNewsVOMapper
11. - [x] FilterDtoRequestMapper
12. - [x] FilterDtoResponseMapper
13. - [x] HabitAssignDtoMapper
14. - [x] HabitAssignManagementDtoMapper
15. - [x] HabitAssignMapper
16. - [x] HabitAssignUserDurationDtoMapper
17. - [x] HabitDtoMapper
18. - [x] HabitFactDtoResponseMapper
19. - [x] HabitManagementDtoMapper
20. - [x] HabitStatisticDtoMapper
21. - [x] HabitStatusCalendarMapper
22. - [x] HabitStatusCalendarVOMapper
23. - [x] HabitTranslationDtoMapper
24. - [x] HabitTranslationMapper
25. - [x] LanguageTranslationDtoMapper
26. - [x] MultipartBase64ImageMapper
27. - [x] NewTagDtoMapper
28. - [x] SearchNewsDtoMapper
29. - [x] ShoppingListItemDtoMapper
30. - [x] ShoppingListItemRequestDtoMapper
31. - [x] ShoppingListItemResponseDtoMapper
32. - [ ] ShoppingListItemWithStatusRequestDtoMapper
33. - [x] TagDtoMapper
34. - [x] TagMapper
35. - [x] TagVOMapper
36. - [ ] UtilsMapper

**Acceptance Criteria:**

* All tests pass successfully.
* The code is clean and adheres to coding standards.
* Dependencies are correctly mocked, and their methods are verified for calls.
* Test coverage should be 100%.

**Comment by ToriForH** [comment]
Viktoriia Herchanivska 1-6 mapper

**Comment by VolodymyrChikh** [comment]
[Volodymyr Chikh] 13-18 mappers

**Comment by IrynaVdovych** [comment]
Iryna Vdovych 19-24 mappers

**Comment by dimonkoval** [comment]
Dmytro Koval 25-30

**Comment by rvolianyk** [comment]
Done 31,33-35
